<a href="https://colab.research.google.com/github/ananxa/NLP-LAB1/blob/main/NLPexp3and4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
input=pd.read_csv('/content/twitter4000.csv')

In [ ]:
input.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   twitts     4000 non-null   object
 1   sentiment  4000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 62.6+ KB

In [ ]:
input.count()

twitts       4000
sentiment    4000
dtype: int64

In [ ]:
input['sentiment'].value_counts()

sentiment
0    2000
1    2000
Name: count, dtype: int64

In [ ]:
input.sample(6)

                                                 twitts  sentiment
1343  @staceyclarkin More than welcome...would love ...          0
3431                     Bedtime!!!  Night Everyone!!!           1
318   @TOUCHOFCLASSENT yeah we closed early like 12:...          0
3857  Twitter sucks, I'm only on here to follow Elle...          1
49    @SonjaCassella Not yet.  Getting some help fro...          0
2319  @Kat_LB thanks lovely!!!  in case you had forg...          1

In [ ]:
input.head()

                                              twitts  sentiment
0  is bored and wants to watch a movie  any sugge...          0
1           back in miami.  waiting to unboard ship           0
2  @misskpey awwww dnt dis brng bak memoriessss, ...          0
3                  ughhh i am so tired  blahhhhhhhhh          0
4  @mandagoforth me bad! It's funny though. Zacha...          0

In [ ]:
pattern = r'\s'
input['twitts'].apply(lambda x:re.sub(pattern,'',x))

0             isboredandwantstowatchamovieanysuggestions?
1                        backinmiami.waitingtounboardship
2       @misskpeyawwwwdntdisbrngbakmemoriessss,IthnkI'...
3                             ughhhiamsotiredblahhhhhhhhh
4       @mandagoforthmebad!It'sfunnythough.ZacharyQuin...
                              ...
3995                                       ijustgraduated
3996                     Templatingworks;itallhastobedone
3997                          mommyjustbroughtmestarbucks
3998        @omareppswatchingyouonaHousere-run...lovinit.
3999    ThanksfortryingtomakemesmileI'llmakeyour18thsp...
Name: twitts, Length: 4000, dtype: object

In [ ]:

pattern = r'\s'
input['Char_count'] = input['twitts'].apply(lambda x:len(re.sub(pattern,'',x)))
input

                                                 twitts  sentiment  Char_count
0     is bored and wants to watch a movie  any sugge...          0          43
1              back in miami.  waiting to unboard ship           0          32
2     @misskpey awwww dnt dis brng bak memoriessss, ...          0          54
3                     ughhh i am so tired  blahhhhhhhhh          0          27
4     @mandagoforth me bad! It's funny though. Zacha...          0         116
...                                                 ...        ...         ...
3995                                  i just graduated           1          14
3996          Templating works; it all has to be done            1          32
3997                   mommy just brought me starbucks           1          27
3998  @omarepps watching you on a House re-run...lov...          1          45
3999  Thanks for trying to make me smile I'll make y...          1          63

[4000 rows x 3 columns]

In [ ]:
input['Word_count'] = input['twitts'].apply(lambda x:len(x.split()))
input

,twitts,sentiment,Char_count,Word_count
0,is bored and wants to watch a movie any sugge...,0,43,10
1,back in miami. waiting to unboard ship,0,32,7
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12
3,ughhh i am so tired blahhhhhhhhh,0,27,6
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26
...,...,...,...,...
3995,i just graduated,1,14,3
3996,Templating works; it all has to be done,1,32,8
3997,mommy just brought me starbucks,1,27,5
3998,@omarepps watching you on a House re-run...lov...,1,45,8
3999,Thanks for trying to make me smile I'll make y...,1,63,16

In [ ]:
input['avg_word_length'] = input['Char_count']/input['Word_count']
input

,twitts,sentiment,Char_count,Word_count,avg_word_length
0,is bored and wants to watch a movie any sugge...,0,43,10,4.300000
1,back in miami. waiting to unboard ship,0,32,7,4.571429
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12,4.500000
3,ughhh i am so tired blahhhhhhhhh,0,27,6,4.500000
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26,4.461538
...,...,...,...,...,...
3995,i just graduated,1,14,3,4.666667
3996,Templating works; it all has to be done,1,32,8,4.000000
3997,mommy just brought me starbucks,1,27,5,5.400000
3998,@omarepps watching you on a House re-run...lov...,1,45,8,5.625000
3999,Thanks for trying to make me smile I'll make y...,1,63,16,3.937500

#**Feature Extraction**

In [ ]:
input['avg_word_length'].apply(lambda x: round(x,2))

0       4.30
1       4.57
2       4.50
3       4.50
4       4.46
        ...
3995    4.67
3996    4.00
3997    5.40
3998    5.62
3999    3.94
Name: avg_word_length, Length: 4000, dtype: float64

In [ ]:
input['hash_tags_count'] = input['twitts'].apply(lambda x:len(re.findall(r'#\w+',x)))
input

,twitts,sentiment,Char_count,Word_count,avg_word_length,hash_tags_count
0,is bored and wants to watch a movie any sugge...,0,43,10,4.300000,0
1,back in miami. waiting to unboard ship,0,32,7,4.571429,0
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12,4.500000,0
3,ughhh i am so tired blahhhhhhhhh,0,27,6,4.500000,0
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26,4.461538,0
...,...,...,...,...,...,...
3995,i just graduated,1,14,3,4.666667,0
3996,Templating works; it all has to be done,1,32,8,4.000000,0
3997,mommy just brought me starbucks,1,27,5,5.400000,0
3998,@omarepps watching you on a House re-run...lov...,1,45,8,5.625000,0
3999,Thanks for trying to make me smile I'll make y...,1,63,16,3.937500,0

In [ ]:
input['mentions_count'] = input['twitts'].apply(lambda x:len(re.findall(r'@\w+',x)))
input

,twitts,sentiment,Char_count,Word_count,avg_word_length,hash_tags_count,mentions_count
0,is bored and wants to watch a movie any sugge...,0,43,10,4.300000,0,0
1,back in miami. waiting to unboard ship,0,32,7,4.571429,0,0
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12,4.500000,0,1
3,ughhh i am so tired blahhhhhhhhh,0,27,6,4.500000,0,0
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26,4.461538,0,1
...,...,...,...,...,...,...,...
3995,i just graduated,1,14,3,4.666667,0,0
3996,Templating works; it all has to be done,1,32,8,4.000000,0,0
3997,mommy just brought me starbucks,1,27,5,5.400000,0,0
3998,@omarepps watching you on a House re-run...lov...,1,45,8,5.625000,0,1
3999,Thanks for trying to make me smile I'll make y...,1,63,16,3.937500,0,0

In [ ]:
input['twitts'].apply(lambda x: len([word for word in x.split() if word.isupper()]))

0       0
1       0
2       1
3       0
4       0
       ..
3995    0
3996    0
3997    0
3998    0
3999    0
Name: twitts, Length: 4000, dtype: int64

In [ ]:
input['twitts'].apply(lambda x: len([word for word in x.split() if word.islower()]))

0       10
1        7
2        9
3        6
4       22
        ..
3995     3
3996     7
3997     5
3998     7
3999    14
Name: twitts, Length: 4000, dtype: int64

In [ ]:
input['twitts'].apply(lambda x:re.sub(r'\s+',' ',x).lower())

0       is bored and wants to watch a movie any sugges...
1                 back in miami. waiting to unboard ship
2       @misskpey awwww dnt dis brng bak memoriessss, ...
3                        ughhh i am so tired blahhhhhhhhh
4       @mandagoforth me bad! it's funny though. zacha...
                              ...
3995                                    i just graduated
3996             templating works; it all has to be done
3997                     mommy just brought me starbucks
3998    @omarepps watching you on a house re-run...lov...
3999    thanks for trying to make me smile i'll make y...
Name: twitts, Length: 4000, dtype: object

In [ ]:
pattern=r'[^\w\s]'
input['twitts'].apply(lambda x:re.sub(pattern,'',x))

0       is bored and wants to watch a movie  any sugge...
1                 back in miami  waiting to unboard ship
2       misskpey awwww dnt dis brng bak memoriessss  I...
3                       ughhh i am so tired  blahhhhhhhhh
4       mandagoforth me bad Its funny though Zachary Q...
                              ...
3995                                    i just graduated
3996             Templating works it all has to be done
3997                     mommy just brought me starbucks
3998      omarepps watching you on a House rerunlovin it
3999    Thanks for trying to make me smile Ill make yo...
Name: twitts, Length: 4000, dtype: object

In [ ]:
pattern=r'[^\w\s]'
input['twitts'].apply(lambda x:re.sub(pattern,'',x))

0       is bored and wants to watch a movie  any sugge...
1                 back in miami  waiting to unboard ship
2       misskpey awwww dnt dis brng bak memoriessss  I...
3                       ughhh i am so tired  blahhhhhhhhh
4       mandagoforth me bad Its funny though Zachary Q...
                              ...
3995                                    i just graduated
3996             Templating works it all has to be done
3997                     mommy just brought me starbucks
3998      omarepps watching you on a House rerunlovin it
3999    Thanks for trying to make me smile Ill make yo...
Name: twitts, Length: 4000, dtype: object

For emails

In [ ]:
pattern = r'\w+@\w+.\w+'
input['twitts'].apply(lambda x:re.findall(pattern=pattern,string = x))

np.int64(4000)

In [ ]:
pattern =r'\b[A-Za-z._+-]+@[A-Za-z.].[A-Z|a-z]{2,}\b' #word boundary
input['email']= input['twitts'].apply(lambda x:re.findall(pattern=pattern,string = x))

0       []
1       []
2       []
3       []
4       []
        ..
3995    []
3996    []
3997    []
3998    []
3999    []
Name: twitts, Length: 4000, dtype: object

In [ ]:
pattern =r'\b[A-Za-z0-9._%+-]+@[A-ZA-ZA-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b' #word boundary
input['email']= input['twitts'].apply(lambda x:",".join(re.findall(pattern=pattern,string = x)))
input

,twitts,sentiment,Char_count,Word_count,avg_word_length,hash_tags_count,mentions_count,email
0,is bored and wants to watch a movie any sugge...,0,43,10,4.300000,0,0,
1,back in miami. waiting to unboard ship,0,32,7,4.571429,0,0,
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12,4.500000,0,1,
3,ughhh i am so tired blahhhhhhhhh,0,27,6,4.500000,0,0,
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26,4.461538,0,1,
...,...,...,...,...,...,...,...,...
3995,i just graduated,1,14,3,4.666667,0,0,
3996,Templating works; it all has to be done,1,32,8,4.000000,0,0,
3997,mommy just brought me starbucks,1,27,5,5.400000,0,0,
3998,@omarepps watching you on a House re-run...lov...,1,45,8,5.625000,0,1,
3999,Thanks for trying to make me smile I'll make y...,1,63,16,3.937500,0,0,

In [ ]:
pattern =r'\b[A-Za-z0-9._%+-]+@[A-ZA-ZA-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b' #word boundary
input['count']= input['twitts'].apply(lambda x:x.count(',')+1 if len(x)>0 else 0)
input

,twitts,sentiment,Char_count,Word_count,avg_word_length,hash_tags_count,mentions_count,email,count
0,is bored and wants to watch a movie any sugge...,0,43,10,4.300000,0,0,,1
1,back in miami. waiting to unboard ship,0,32,7,4.571429,0,0,,1
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12,4.500000,0,1,,2
3,ughhh i am so tired blahhhhhhhhh,0,27,6,4.500000,0,0,,1
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26,4.461538,0,1,,1
...,...,...,...,...,...,...,...,...,...
3995,i just graduated,1,14,3,4.666667,0,0,,1
3996,Templating works; it all has to be done,1,32,8,4.000000,0,0,,1
3997,mommy just brought me starbucks,1,27,5,5.400000,0,0,,1
3998,@omarepps watching you on a House re-run...lov...,1,45,8,5.625000,0,1,,1
3999,Thanks for trying to make me smile I'll make y...,1,63,16,3.937500,0,0,,1

For URLs

In [ ]:
pattern =r'http\S+|www\S+'
input['URLs']= input['twitts'].apply(lambda x:",".join(re.findall(pattern=pattern,string = x)))
input['URL_count']= input['twitts'].apply(lambda x:x.count(',')+1 if len(x)>0 else 0)
input

,twitts,sentiment,Char_count,Word_count,avg_word_length,hash_tags_count,mentions_count,email,count,URLs,URL_count
0,is bored and wants to watch a movie any sugge...,0,43,10,4.300000,0,0,,1,,1
1,back in miami. waiting to unboard ship,0,32,7,4.571429,0,0,,1,,1
2,"@misskpey awwww dnt dis brng bak memoriessss, ...",0,54,12,4.500000,0,1,,2,wwww,2
3,ughhh i am so tired blahhhhhhhhh,0,27,6,4.500000,0,0,,1,,1
4,@mandagoforth me bad! It's funny though. Zacha...,0,116,26,4.461538,0,1,,1,,1
...,...,...,...,...,...,...,...,...,...,...,...
3995,i just graduated,1,14,3,4.666667,0,0,,1,,1
3996,Templating works; it all has to be done,1,32,8,4.000000,0,0,,1,,1
3997,mommy just brought me starbucks,1,27,5,5.400000,0,0,,1,,1
3998,@omarepps watching you on a House re-run...lov...,1,45,8,5.625000,0,1,,1,,1
3999,Thanks for trying to make me smile I'll make y...,1,63,16,3.937500,0,0,,1,,1